CI: Use leap based image because of current Tumbleweed python package problems
openqa-salt-states gitlab CI pipelines fail, likely since some change in
upstream Tumbleweed, e.g. in
https://gitlab.suse.de/openqa/salt-states-openqa/-/jobs/322945#L5895
with:

```
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.8/site-packages/salt/state.py", line 1987, in call
                  # duration in milliseconds.microseconds
                File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2031, in wrapper
                  # improperly loaded
                File "/usr/lib/python3.8/site-packages/salt/states/pkg.py", line 1865, in installed
                  pkg_ret = __salt__["pkg.install"](
                File "/usr/lib/python3.8/site-packages/salt/modules/zypperpkg.py", line 1662, in install
                  __zypper__(
                File "/usr/lib/python3.8/site-packages/salt/modules/zypperpkg.py", line 336, in __call
                  self.__call_result = __salt__["cmd.run_all"](cmd, **kwargs)
                File "/usr/lib/python3.8/site-packages/salt/loader.py", line 1269, in __getitem__
                File "/usr/lib/python3.8/site-packages/salt/utils/lazy.py", line 111, in __getitem__
              KeyError: 'cmd.run_all'
```

I assume this is because of recent changes in upstream Tumbleweed.

This commit replaces the Tumbleweed based container image with one based on
Leap which might give us better results temporarily.

Related progress issue: https://progress.opensuse.org/issues/87970