Replace logrotate cron with systemd timer override to not conflict with daily run
This should fix the problem that on a daily base at midnight we receive
a problem report with:

```
running hourly cronjob scripts

SCRIPT: logrotate exited with RETURNCODE = 1.
```

Multiple calls to logrotate do not pose a problem even if we do not
exclude other logrotate configs. logrotate detects if a logrotation is
necessary for each configured component:

```
error: destination /var/log/apache2/access_log-20191129.xz already exists, skipping rotation
error: destination /var/log/apache2/openqa.access_log-20191129.xz already exists, skipping rotation
error: destination /var/log/rsyncd.log-20191129.xz already exists, skipping rotation
```