Fix telegraf check, 2nd attempt
So the syntax that was originally intended

    ! telegraf test ... && grep

to negate the result apparently does not behave the same in an
interactive bash as in a salt cmd.run.

    % salt --hide-timeout worker3.oqa.suse.de cmd.run '! sudo telegraf --test --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ 2>&1 | grep " E\! "'
    worker3.oqa.suse.de:
    ERROR: Minions returned with non-zero exit code
    % echo $?
    1

    % ! telegraf --test --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ 2>&1 | grep " E\! "
    % echo $?
    0

So now I just grep again for E! in the logfile after salt finishes.