Fix grain to check for Hypervisor
This fixes the error message
```
TypeError: __init__() missing 1 required positional argument: 'args'
```

observed in production (see https://progress.opensuse.org/issues/94994).

Tested via `salt-call --local grains.items` on `openqaworker12` (before and
after the change).